### PR TITLE
Adding a limiter exempt health route

### PR DESCRIPTION
**Pull request by devinmatte**
Help us detect the health of the service

### CODE REVIEW

**Review by mxmeinhold — APPROVED** [review]
LGTM. Would you see if you can resolve checks before merging?

**Comment by devinmatte** [comment]
```
The conflict is caused by:
    The user requested python-ldap==3.3.1
    csh-ldap 2.2.0 depends on python-ldap==3.0.0
```
The new resolver is finding problems. We need to update csh-ldap imo

**Comment by mxmeinhold** [comment]
Your plan to squash this or wait on updates to csh-ldap?

**Comment by devinmatte** [comment]
I think I'm going to merge this instead of waiting. This route is quite useful to have

**Comment by mxmeinhold** [comment]
🚢 🇮🇹

**Pull request merged**
